import { Inter } from "next/font/google";
import "./globals.css";
import ThemeContext from "@/context/ThemeContext";
import Header from "@/components/navigation/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContext>
          <Header />
          {children}
        </ThemeContext>
      </body>
    </html>
  );
}
